# -*- coding: utf-8 -*-
"""Rigor and Reproducibility assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQcGtcCWZAsmN8qDs9hhAb12G5xtrCJv
"""

# October 30th, 2024
#printed simple arithmatic operation:
10+5

#One of the most significant advantages of using repositories is the facilitation of collaboration among researchers.
#By storing code, data, and documentation in a shared environment, teams can work together more effectively, regardless of their geographic locations.
#Version control systems, like Github, enable researchers to track changes, revert to previous versions, and maintain a history of modifications.
# This ensures that the entire research process can be scrutinized and replicated, allowing others to follow the same steps taken to reach conclusions.
#Repositories encourage comprehensive documentation of methodologies, including code comments, README files, and structured directories for datasets.
#This level of documentation is crucial for reproducibility, as it provides clear instructions on how to set up the environment, run the analysis, and interpret the results.
#A well-documented repository serves as a self-contained package that others can use to replicate the study, making it easier for new researchers to understand and build upon previous work.
#Additionally, increasing data and code transparency help foster scientific practices that are open and trustworthy.